export const categories = {
  'accesskeys': 'A11Y Navigation',
  'aria-allowed-attr': 'A11Y - ARIA Attribute',
  'aria-allowed-role': 'A11Y - ARIA Attribute',
  'aria-command-name': 'A11Y - ARIA Attribute',
  'aria-conditional-attr': 'A11Y - ARIA Attribute',
  'aria-deprecated-role': 'A11Y - ARIA Attribute',
  'aria-dialog-name': 'A11Y - ARIA Attribute',
  'aria-Hidden-body': 'A11Y - ARIA Attribute',
  'aria-Hidden-focus': 'A11Y - ARIA Attribute',
  'aria-input-field-name': 'A11Y - ARIA Attribute',
  'aria-meter-name': 'A11Y - ARIA Attribute',
  'aria-progressbar-name': 'A11Y - ARIA Attribute',
  'aria-prohibited-attr': 'A11Y - ARIA Attribute',
  'aria-required-attr': 'A11Y - ARIA Attribute',
  'aria-required-children': 'A11Y - ARIA Attribute',
  'aria-required-parent': 'A11Y - ARIA Attribute',
  'aria-roles': 'A11Y - ARIA Attribute',
  'aria-text': 'A11Y - ARIA Attribute',
  'aria-toggle-field-name': 'A11Y - ARIA Attribute',
  'aria-tooltip-name': 'A11Y - ARIA Attribute',
  'aria-treeitem-name': 'A11Y - ARIA Attribute',
  'aria-valid-attr': 'A11Y - ARIA Attribute',
  'aria-valid-attr-value': 'A11Y - ARIA Attribute',
  'bootup-time': 'Diagnostics',
  'button-name': 'A11Y Names Labels',
  'bypass': 'A11Y Navigation',
  'canonical': 'SEO Content',
  'charset': 'Best Practices Browser Compatibility',
  'color-contrast': 'A11Y - Color Contrast',
  'crawlable-anchors': 'SEO Crawl',
  'critical-request-chains': 'Diagnostics',
  'csp-xss': 'Best Practices - Trust Safety',
  'cumulative-layout-shift': 'Metrics',
  'definition-list': 'A11Y - Tables Lists',
  'deprecations': 'Best Practices General',
  'Diagnostics': 'Hidden',
  'dlitem': 'A11Y - Tables Lists',
  'doctype': 'Best Practices Browser Compatibility',
  'document-title': 'SEO Content',
  'dom-size': 'Diagnostics',
  'duplicate-id-aria': 'A11Y - ARIA Attribute',
  'duplicated-javascript': 'Diagnostics',
  'efficient-animated-content': 'Diagnostics',
  'empty-heading': 'Hidden',
  'errors-in-console': 'Best Practices General',
  'final-screenshot': 'Hidden',
  'first-contentful-paint': 'Metrics',
  'first-meaningful-paint': 'Hidden',
  'font-display': 'Diagnostics',
  'font-size': 'Best Practices - User Experience',
  'form-field-multiple-labels': 'A11Y Names Labels',
  'frame-title': 'A11Y Names Labels',
  'geolocation-on-start': 'Best Practices - Trust Safety',
  'heading-order': 'A11Y Navigation',
  'hreflang': 'SEO Content',
  'html-has-lang': 'A11Y Language',
  'html-lang-valid': 'A11Y Language',
  'html-xml-lang-mismatch': 'A11Y Language',
  'http-status-code': 'SEO Crawl',
  'identical-links-same-purpose': 'Hidden',
  'image-alt': 'SEO Content',
  'image-aspect-ratio': 'Best Practices - User Experience',
  'image-redundant-alt': 'A11Y Names Labels',
  'image-size-responsive': 'Best Practices - User Experience',
  'input-button-name': 'A11Y Names Labels',
  'input-image-alt': 'A11Y Names Labels',
  'inspector-issues': 'Best Practices General',
  'interactive': 'Hidden',
  'is-crawlable': 'SEO Crawl',
  'is-on-https': 'Best Practices - Trust Safety',
  'js-libraries': 'Best Practices General',
  'label': 'A11Y Names Labels',
  'label-content-name-mismatch': 'Hidden',
  'landmark-one-main': 'Hidden',
  'largest-contentful-paint': 'Metrics',
  'largest-contentful-paint-element': 'Diagnostics',
  'layout-shifts': 'Diagnostics',
  'lcp-lazy-loaded': 'Diagnostics',
  'legacy-javascript': 'Diagnostics',
  'link-in-text-block': 'A11Y - Color Contrast',
  'link-name': 'A11Y Names Labels',
  'link-text': 'SEO Content',
  'list': 'A11Y - Tables Lists',
  'listitem': 'A11Y - Tables Lists',
  'long-tasks': 'Diagnostics',
  'main-thread-tasks': 'Hidden',
  'mainthread-work-breakdown': 'Diagnostics',
  'max-potential-fid': 'Hidden',
  'meta-description': 'SEO Content',
  'meta-refresh': 'A11Y - Best Practices',
  'meta-viewport': 'A11Y - Best Practices',
  'Metrics': 'Hidden',
  'modern-image-formats': 'Diagnostics',
  'network-requests': 'Hidden',
  'network-rtt': 'Hidden',
  'network-server-latency': 'Hidden',
  'no-document-write': 'Diagnostics',
  'non-composited-animations': 'Diagnostics',
  'notification-on-start': 'Best Practices - Trust Safety',
  'object-alt': 'A11Y Names Labels',
  'offscreen-images': 'Diagnostics',
  'paste-preventing-inputs': 'Best Practices - User Experience',
  'prioritize-lcp-image': 'Diagnostics',
  'redirects': 'Diagnostics',
  'redirects-http': 'Best Practices - Trust Safety',
  'render-blocking-resources': 'Diagnostics',
  'resource-summary': 'Hidden',
  'robots-txt': 'SEO Crawl',
  'screenshot-thumbnails': 'Hidden',
  'script-treemap-data': 'Hidden',
  'select-name': 'A11Y Names Labels',
  'server-response-time': 'Diagnostics',
  'skip-link': 'A11Y Names Labels',
  'speed-index': 'Metrics',
  'tabindex': 'A11Y Navigation',
  'table-duplicate-name': 'A11Y - Tables Lists',
  'table-fake-caption': 'Hidden',
  'target-size': 'A11Y - Best Practices',
  'td-has-header': 'Hidden',
  'td-headers-attr': 'A11Y - Tables Lists',
  'th-has-data-cells': 'A11Y - Tables Lists',
  'third-party-cookies': 'Best Practices General',
  'third-party-facades': 'Diagnostics',
  'third-party-summary': 'Diagnostics',
  'total-blocking-time': 'Metrics',
  'total-byte-weight': 'Diagnostics',
  'unminified-css': 'Diagnostics',
  'unminified-javascript': 'Diagnostics',
  'unsized-images': 'Diagnostics',
  'unused-css-rules': 'Diagnostics',
  'unused-javascript': 'Diagnostics',
  'user-timings': 'Diagnostics',
  'uses-long-cache-ttl': 'Diagnostics',
  'uses-optimized-images': 'Diagnostics',
  'uses-passive-event-listeners': 'Diagnostics',
  'uses-rel-preconnect': 'Diagnostics',
  'uses-responsive-images': 'Diagnostics',
  'uses-text-compression': 'Diagnostics',
  'valid-lang': 'A11Y Language',
  'valid-source-maps': 'Best Practices General',
  'video-caption': 'A11Y Audio Video',
  'viewport': 'Diagnostics'
}